Added 'set -e' to scripts.

diff --git a/check-git-branches b/check-git-branches
--- a/check-git-branches
+++ b/check-git-branches
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Immediately stop on any command that fails
+set -e
+
 quiet=$1
 
 if [ "$#" -gt 1 ]; then
